### ISSUE TITLE
如果我要批量写入Excel呢？

### ISSUE THREAD

**Issue by q979713444** [zhouzhuo810/ZzExcelCreator#1]
![image](https://user-images.githubusercontent.com/8711413/36778053-9e7e408c-1ca6-11e8-9895-bfbf65b476bb.png)

这样操作起来就有点麻烦了，每次都要open和close么

**Comment by zhouzhuo810** [comment]
不用每次都open，open会得到一个实例，操作完，最后再close就好了

**Comment by zhouzhuo810** [comment]
参考读数据，一个道理
