### ISSUE TITLE
超出最大列数

### ISSUE THREAD

**Issue by UserNameQC** [zhouzhuo810/ZzExcelCreator#7]
数据写入时，报 超出最大列数，有时会内存溢出。请问一下，生成的表格是那个版本的，查资料2003版最大行数是65536行，最大列数是256列。Excel2007及以后的版本最大行数是1048576行，最大列数是16384列。我用的时候 列数最大有600多列，行大概也就600。

**Comment by zhouzhuo810** [comment]
https://blog.csdn.net/yangdan410183767/article/details/78497958

**Comment by UserNameQC** [comment]
收到，多谢，去试一下。
